# Gradle Configuration
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true
android.gradle.jetifier.ignorelist=androidx

# Kotlin Compiler Configuration
kotlin.jvm.target=17
kotlin.skipMetadataVersionCheck=true
